# Generated by Django 3.0.8 on 2020-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('he_id', models.AutoField(primary_key=True, serialize=False)),
                ('he_hospital_id', models.CharField(max_length=100, null=True)),
                ('he_name', models.CharField(max_length=100)),
                ('he_type', models.CharField(max_length=20)),
                ('he_mobile', models.IntegerField(null=True)),
                ('enable_otp', models.CharField(max_length=20, null=True)),
                ('he_otp', models.IntegerField(null=True)),
                ('he_is_otp_verify', models.IntegerField(null=True)),
                ('status', models.TextField()),
                ('formstatus', models.CharField(max_length=100, null=True)),
                ('he_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
