# Generated by Django 3.0.8 on 2020-07-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='example',
            table='hospital_employee',
        ),
    ]
